name : Build Unity project

on:
  push:
    branches:
      - SNAKE-22

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name : Checkout repository
        uses: actions/checkout@v4.2.2
      - id: cache-unity
        name: Cache Unity packages    
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-unity-
      #Installer Android SDK, JDK, et NDK
      - name: Install Android SDK, JDK, NDK
        run: |
          # Installer les dépendances système nécessaires
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
      - name: Activate Unity License
        run: |
          mkdir -p $HOME/.local/share/unity3d
          echo "$UNITY_LICENSE_FILE"
          echo "$UNITY_LICENSE_FILE" > $HOME/.local/share/unity3d/UnityEntitlementLicense.xml
        env:
          UNITY_LICENSE_FILE: ${{ secrets.UNITY_LICENSE_FILE }}
      # Set up Unity
      - name : Set up Unity project
        uses: game-ci/unity-builder@v4.5.0
        with:
          version: 2022.3.22f1
          targetPlatform: StandaloneAndroid 
          projectPath: .
          buildName: SnakeAndroidBuild
          buildPath: ./builds/android
          customParameters: '-batchmode -nographics -quit -logFile ./builds/android/unity_build_log.txt -buildTarget StandaloneAndroid -outputPath ./builds/android/SnakeAndroidBuild.apk'
      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: SnakeAndroidBuild-${{ github.sha }}-v2022.3.22f1.apk
          path: ./builds/android/SnakeAndroidBuild.apk
      - name: Upload Unity build logs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: UnityBuildLogs
          path: ./builds/android/unity_build_log.txt
